print("hello"+"world")
print("helloworld")
print("hello+world")
print("my name is bhavya")
print("branch.CSM")
print("section 1")
print("18 years old")
print("i am from nekunambadu")
print("i am pursing my b tech in NRIIT DTBU IN AGIRIPALLI")
print('ok byee..')
